
# ==========================================
# Stage 3: Build Deploy
# ==========================================
FROM tomcat:9.0.108-jdk8-temurin-noble AS deploy

RUN rm -rf /usr/local/tomcat/webapps/*
RUN rm -rf /usr/local/tomcat/webapps.dist
RUN sed -i '/<\/web-app>/i \
    <error-page>\n\
      <exception-type>java.lang.Throwable<\/exception-type>\n\
      <location>/error.html<\/location>\n\
    <\/error-page>\n \
    <error-page>\n\
      <error-code>0<\/error-code>\n\
      <location>/error.html<\/location>\n\
    <\/error-page>\n' /usr/local/tomcat/conf/web.xml
COPY ./error.html /usr/local/tomcat/webapps/ROOT/error.html
COPY ./cds-tcamt-controller/target/fits.war /usr/local/tomcat/webapps/fits.war

COPY ./.env.dev /usr/local/tomcat/.env.dev
COPY dev/dev-entrypoint.sh /usr/local/tomcat/entrypoint.sh
RUN chmod +x /usr/local/tomcat/entrypoint.sh

EXPOSE 9095
ENTRYPOINT ["/usr/local/tomcat/entrypoint.sh"]